### ISSUE TITLE
[Proposal] Checkbox

### ISSUE THREAD

**Issue by jamesmontemagno** [FormsCommunityToolkit/Controls#1]
## Proposal:
Implementation to have a checkbox with 2 states:
Selected, Unselected

## Properties
boolean: IsChecked: Gets or sets the checked state
boolean: IsEnabled: Gets or sets enabled status

## Events
OnCheckChanged: Triggered when check status changes.

## Implementation
Android: Built in control
iOS: Custom UIButton with graphics
UWP: Built in control

**Comment by bartlannoeye** [comment]
This issue was moved to FormsCommunityToolkit/FormsCommunityToolkit#4
